runtime: python39
entrypoint: uvicorn app.main:app --host 0.0.0.0 --port $PORT

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 20

env_variables:
  GCP_PROJECT: 47859746837
